import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Intercepting Routes Sample",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <div className={"p-5"}>{children}</div>
      </body>
    </html>
  );
}
